export default {
    VIEW_ALL_CLIENTS: "VIEW_ALL_CLIENTS",
    VIEW_SEARCHED_CLIENT: "VIEW_SEARCHED_CLIENT",
    ADD_NEW_CLIENT: "ADD_NEW_CLIENT",
    EDIT_CLIENT: "EDIT_CLIENT",
    DELETE_CLIENT: "DELETE_CLIENT",
}