export default {
    FETCH_ITEMS_REQUESTED: "FETCH_ITEMS_REQUESTED",
    SHOW_FETCHED_ITEMS: "SHOW_FETCHED_ITEMS",
    FILTER_ITEMS: "FILTER_ITEMS",
    ADD_TO_CART: "ADD_TO_CART",
    REMOVE_FROM_CART: "REMOVE_FROM_CART",
    INCREMENT_IN_CART: "INCREMENT_IN_CART",
    DECREMENT_FROM_CART: "DECREMENT_FROM_CART"
}